language: php
dist: trusty
sudo: required
env:
  - HHVM=false
  - PHPUNIT=phpunit

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm
      env:
        - HHVM=true
        - PHPUNIT=./vendor/bin/phpunit

install:
  - composer install
  - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

before_script:
  - mkdir -p build/logs
  - cd tests

script:
  - $PHPUNIT --colors --coverage-clover ../build/logs/clover.xml .

after_success:
  - cd ..
  - php vendor/bin/coveralls --config .coveralls.yml -v
