language: php

php:
  - 5.0
  - 5.1
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - mkdir -p build/logs
  - cd tests

script:
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/php-loremipsum/build/logs/clover.xml ./tests

after_success:
  - php vendor/bin/coveralls --config ../.coveralls.yml -v
