language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  include:
    - php: nightly
      env: ALLOW_FAILURE=1
    - php: hhvm-nightly
      env: ALLOW_FAILURE=1
  allow_failures:
    - env: ALLOW_FAILURE=1

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - cd tests

script:
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/php-loremipsum/build/logs/clover.xml .

after_success:
  - php ../vendor/bin/coveralls --config ../.coveralls.yml -v
