language: php
dist: trusty
sudo: required

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm-3.3
    - php: hhvm-3.6
    - php: hhvm-3.9
    - php: hhvm-3.12
    - php: hhvm-3.15
    - php: hhvm-3.18

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - cd tests
  - phpunit --version

script:
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/php-loremipsum/build/logs/clover.xml .

after_success:
  - php ../vendor/bin/coveralls --config ../.coveralls.yml -v
